testname: MUSHRA TEST 
testId: Speech Enhacemenet
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: generic
      id: first_page
      name: Welcome
      content: Welcome to MUSHRA Test! If possible open it in you PC/Laptops       
    - type: mushra
      id: trial1
      name: MUSHRA
      content: This page is just for the training purpose i.e how to do this test in the furthur pages. Please perform the underlined instructions to proceed with the training session. So what you have to do is listen to the refrence audio(present on the left) and than the target audios present on the right,and give score to the target audio out off 100. Reminder: In a MUSHRA listening test you are asked to rate the Basic Audio Quality (BAQ) of each condition.<br/>Basic Audio Quality is a single and global attribute that is used to judge any and all detected differences between the reference and the condition.
      showWaveform: true
      enableLooping: true 
      reference: configs/resources/audio/dt/mono_ref.wav
      createAnchor35: true
      createAnchor70: true
      stimuli:
          C1: configs/resources/audio/dt/mono_c1.wav
          C2: configs/resources/audio/dt/mono_c2.wav
          C3: configs/resources/audio/dt/mono_c3.wav
    - 
          - random
          - type: mushra
            id: Experiment_1_trail_dt
            name: MUSHRA - Random 2
            content: Due to randomization, this page will be either the second MUSHRA page or the third MUSHRA page.
            enableLooping: true 
            reference: configs/resources/audio/dt/mono_ref.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/resources/audio/dt/mono_c1.wav
                C2: configs/resources/audio/dt/mono_c2.wav
                C3: configs/resources/audio/dt/mono_c3.wav          
          - type: mushra
            id: Experiment_1_trail_dt
            name: MUSHRA - Random 1
            content: Due to randomization, this page will be either the second MUSHRA page or the third MUSHRA page.
            enableLooping: true 
            reference: configs/resources/audio/dt/mono_ref.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/resources/audio/dt/mono_c1.wav
                C2: configs/resources/audio/dt/mono_c2.wav
                C3: configs/resources/audio/dt/mono_c3.wav
          - type: mushra
            id: Experiment_2_trail_et
            name: MUSHRA - Random 1
            content: Due to randomization, this page will be either the second MUSHRA page or the third MUSHRA page.
            enableLooping: true
            reference: configs/resources/audio/et/mono_ref.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/resources/audio/et/mono_c1.wav
                C2: configs/resources/audio/et/mono_c2.wav
                C3: configs/resources/audio/et/mono_c3.wav
          - type: mushra
            id: Experiment_2_trail_et
            name: MUSHRA - Random 2
            content: Due to randomization, this page will be either the second MUSHRA page or the third MUSHRA page.
            enableLooping: true
            reference: configs/resources/audio/et/mono_ref.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/resources/audio/et/mono_c1.wav
                C2: configs/resources/audio/et/mono_c2.wav
                C3: configs/resources/audio/et/mono_c3.wav
    - type: finish
      name: Thank you
      content: Thank you for attending! Pls take screenshot of the result that will come and send it to Rohit.K
      showResults: true
      writeResults: true
      questionnaire:
          - type: text
            label: eMail
            name: email
          - type: number
            label: Age
            name: age
            min: 0
            max: 100
            default: 30
          - type: likert
            name: gender
            label: Gender
            response:
             - value: female
               label: Female
             - value: male
               label: Male
             - value: other
               label: Other
